name: bungee_ksa
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  firebase_core: ^3.4.0
  google_fonts: ^6.2.1
  path_provider:
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cloud_firestore: ^5.4.0
  barcode_widget: ^2.0.4
  email_validator: ^3.0.0
  bloc: ^8.1.4
  barcode_scan2: ^4.3.3
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.2
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.0
  image_picker: ^1.1.2
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.7.2  # Add intl_utils for localization generation

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/slogan.png
    - assets/images/step1.png    
    - assets/images/step2.png  
    - assets/images/step3.png
    - assets/images/step4.png   
    - assets/images/1.jpeg    
    - assets/images/2.jpg  
    - assets/images/3.jpeg
    - assets/images/4.jpg   
    - assets/images/trainer.png
    - assets/images/barcode.png 
    - assets/images/limited_offer.png
    - assets/animations/checkmark.json
