// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmBaXL4IczubDFdkrtE0BZ4MywIEP-qMk',
    appId: '1:363843415136:web:73b3acadc83e665d49e705',
    messagingSenderId: '363843415136',
    projectId: 'bungeeksa',
    authDomain: 'bungeeksa.firebaseapp.com',
    storageBucket: 'bungeeksa.appspot.com',
    measurementId: 'G-QX59Z10GLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82aIVyX5mfyXCKRtfScENmGBao6wEe5k',
    appId: '1:363843415136:android:44e71dfb508bbf3249e705',
    messagingSenderId: '363843415136',
    projectId: 'bungeeksa',
    storageBucket: 'bungeeksa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEI6fxVTG32VjRxtlQr6rwl8xdaqMAVCw',
    appId: '1:363843415136:ios:478741e333d69e3b49e705',
    messagingSenderId: '363843415136',
    projectId: 'bungeeksa',
    storageBucket: 'bungeeksa.appspot.com',
    iosBundleId: 'com.example.bungeeKsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEI6fxVTG32VjRxtlQr6rwl8xdaqMAVCw',
    appId: '1:363843415136:ios:478741e333d69e3b49e705',
    messagingSenderId: '363843415136',
    projectId: 'bungeeksa',
    storageBucket: 'bungeeksa.appspot.com',
    iosBundleId: 'com.example.bungeeKsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmBaXL4IczubDFdkrtE0BZ4MywIEP-qMk',
    appId: '1:363843415136:web:40bbbe9d54088d9d49e705',
    messagingSenderId: '363843415136',
    projectId: 'bungeeksa',
    authDomain: 'bungeeksa.firebaseapp.com',
    storageBucket: 'bungeeksa.appspot.com',
    measurementId: 'G-QB9S27QDF0',
  );
}
